name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Убедись, что твоя основная ветка называется main (или замени на master)

# Даем права на запись для публикации Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Решаем проблему с предупреждением о Node.js 20
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Ставим версию как у тебя на компьютере

      - name: Enable Corepack (Fix for Yarn 4)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      # Опционально: можно запустить проверки перед сборкой
      # - name: Run lint
      #   run: yarn lint
      # - name: Run tests
      #   run: yarn test

      - name: Build project
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # ВАЖНО: папка, куда Webpack собирает проект. Обычно это dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
